language: node_js
node_js:
  - "5.10.1"
env:
  - DATABASE_URL="postgres://postgres@localhost/crudtest" PORT="5000"
notifications:
   slack: devops-training-spb:7C6VUojq9xStvnITcVFUHWag
services:
  - postgresql
before_script:
  - psql -c 'create database crudtest;' -U postgres